### ISSUE TITLE
Just a question. 

### ISSUE THREAD

**Issue by ReneFroger** [pelodelfuego/vim-swoop#1]
Thanks for sharing this plugin! It works fast and well nicely, I'm impressed. 

I wonder if you already knew Unite line, as stated in the video https://www.youtube.com/watch?v=fwqhBSxhGU0 from 20:00? 

It have same functionality as Vim Swoop, except Vim Swoop is able to have multiple buffers, while Unite line source will only work on one buffer. But I believe you can configure Unite source to do that. 

I was just wondering, if you knew there was already an alternative for helm-swoop in Unite line.

**Comment by ReneFroger** [comment]
I just checked it. And indeed, it works much better now. 

Thanks!

**Comment by pelodelfuego** [comment]
Thanks for the feedback, i'm finishing documentation and merge to master soon. I Hope people will envoy it !
