### ISSUE TITLE
Regex mode, ignore-case etc.

### ISSUE THREAD

**Issue by jeetsukumaran** [pelodelfuego/vim-swoop#11]
- "Regex" mode is misleading. It implies that the pattern searched will be treated as a regular expression, but instead all it means is that a typed space is substituted with ``.*``.

- I suggest that something more explicit be used, e.g. ``let g:swoopSpaceInsertsWildcard = 0``

- Forcing case-insensitivity is problematic (the "``\c``" flag in ``getSwoopPattern()``).

- I suggest the following *actual* Swoop modes:

  (1) plaintext, follow ``ignorecase`` (as default)
  (2) plaintext, case-insensitive
  (3) plaintext, case-sensitive
  (4) regular-expression

- Or, perhaps simpler:

  (1) regular-expression, follow ``ignorecase`` (as default)
  (2) regular-expression, force case-insensitive
  (3) regular-expression, force case-sensitive

- This would be easy to implement: the function ``getSwoopPattern()`` would simply interpret the pattern appropriately, and wrap/escape as needed.

- I suggest a Swoop-buffer-specific key-mapping (i.e., only available from within the swoop) to cycle between these modes

- I can implement these and submit a pull request, but may not get a chance to do so before next week.

**Comment by pelodelfuego** [comment]
RegexMode
I agree, yours are better semantic choices

Case insensitivity
It is only for highlighting the pattern, i've plan to add smartcase search which would improve the part of swoop

Regular expression
Actually, search is already a combine of the modes you are talking about, if you type: ```[0-9] ;``` the search pattern would be ```[0-9].*;``` .
However, don't know if you notice but to search ```]```, you will need to escape it like ```\]```.
I'm thinking about introduce a mode for regex escape but it is not the priority

For now I would like to focus on more urgent issues and get a stable and well proved release (ie undo and save issue).
But once reached, why not introduce these advanced functionality.

**Comment by pelodelfuego** [comment]
Just push a new commit which should match your request.
