### ISSUE TITLE
Error of no 'previous search' on a clean install

### ISSUE THREAD

**Issue by jonthn** [pelodelfuego/vim-swoop#12]
I just installed on a new machine my vim configuration with 'vim-swoop' and when I issued either ```:Swoop``` or ```:Swoop!``` I got this

```
Error detected while processing function <SNR>48_cursorMoved..<SNR>48_displaySwoopResult..<SNR>48_getSwoopResultsLine:
line    7:
E35: No previous regular expression
Error detected while processing function <SNR>48_cursorMoved..<SNR>48_displaySwoopResult..<SNR>48_getSwoopResultsLine:
line    7:
E476: Invalid command
Press ENTER or type command to continue
```
It seems by adding the code below fix this issue in ```s:getSwoopResultsLine(bufferList, pattern)``` before the loop : 
```
     if empty(a:pattern)
         return results
     endif
```

**Comment by pelodelfuego** [comment]
Hum, strange issue,

What is your vim version?
Can you provide me a minimal Exemple ? (ie file you were working on and the exact command you typed)

Does it append with ```:call SwoopMulti(pattern)``` ?

Your hotfix seems good for this case but you're cutting off a functionality which is to swoop last search pattern.

**Comment by jonthn** [comment]
Below a 'minimal' vimrc to reproduce this error : 
```
" vim:fdm=marker
"
scriptencoding utf-8

" basically vi rest in peace
set nocompatible

" set EDITORHOME to the root directory of the plug-ins and vim user files
let $EDITORHOME=get(split(&runtimepath, ','), 0)

" Utilities functions ----------------------------------------------------- {{{
function! CheckMake_dir(dir)
  if exists("*mkdir")
    if !isdirectory(a:dir)
      call mkdir(a:dir, 'p')
    endif
  endif
  return isdirectory(a:dir)
endfunction

" }}}

" Prefer POSIX shell
if &shell =~# 'fish$'
  set shell=/bin/sh
endif

let g:plug_window = "below new"

" Plugins Manager --------------------------------------------------------- {{{

if has('vim_starting')

  let s:plugins_manager_url = 'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  let s:plugins_manager_corefile = $EDITORHOME . '/' . 'autoload/plug.vim'

  " check the plug-ins manager is installed
  function! CheckPluginsManager()
    return !empty(glob(s:plugins_manager_corefile))
  endfunction

  " function to detect and install if it's not the case the plug-ins manager
  function! PluginsManagerOnDisk()
    if !CheckPluginsManager()
      if 1 == confirm("Install plugins manager ?", "&Yes\n&No", 2)
	if CheckMake_dir(fnamemodify(s:plugins_manager_corefile, ":p:h"))
	  if executable('curl')
	    execute '!curl -fLo '. s:plugins_manager_corefile . ' ' . s:plugins_manager_url
	    if !v:shell_error
	      if has("autocmd")
		autocmd VimEnter * PlugInstall
	      endif
	    endif
	  elseif executable('wget')
	    execute '!wget -O '. s:plugins_manager_corefile . ' ' . s:plugins_manager_url
	    if !v:shell_error
	      if has("autocmd")
		autocmd VimEnter * PlugInstall
	      endif
	    endif
	  else
	    echohl ErrorMsg | echomsg "curl or wget necessary" | echohl NONE
	  endif
	else
	  echohl ErrorMsg | echomsg "No plug-ins manager found!" | echohl NONE
	endif
      endif
    endif
  endfunction

  call PluginsManagerOnDisk()

endif

try
  call plug#begin()

  Plug 'pelodelfuego/vim-swoop'

  call plug#end()

catch
finally
endtry
```
Usually to reproduce this problem I remove ```.vim/``` and ```.viminfo```
You can then simply edit this vimrc and issue the command ```:Swoop!```

I tried SwoopMulti like this : 
```
:call SwoopMulti('nocomp')
```
and I get this error : 
```
E118: Too many arguments for function: SwoopMulti
```

My vim version : 
```
VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Sep  9 2014 16:30:51)
Compiled by root@apple.com
Normal version without GUI.  Features included (+) or not (-):
-arabic +autocmd -balloon_eval -browse +builtin_terms +byte_offset +cindent 
-clientserver -clipboard +cmdline_compl +cmdline_hist +cmdline_info +comments 
-conceal +cryptv +cscope +cursorbind +cursorshape +dialog_con +diff +digraphs 
-dnd -ebcdic -emacs_tags +eval +ex_extra +extra_search -farsi +file_in_path 
+find_in_path +float +folding -footer +fork() -gettext -hangul_input +iconv 
+insert_expand +jumplist -keymap -langmap +libcall +linebreak +lispindent 
+listcmds +localmap -lua +menu +mksession +modify_fname +mouse -mouseshape 
-mouse_dec -mouse_gpm -mouse_jsbterm -mouse_netterm -mouse_sysmouse 
+mouse_xterm +multi_byte +multi_lang -mzscheme +netbeans_intg -osfiletype 
+path_extra -perl +persistent_undo +postscript +printer -profile +python/dyn 
-python3 +quickfix +reltime -rightleft +ruby/dyn +scrollbind +signs 
+smartindent -sniff +startuptime +statusline -sun_workshop +syntax +tag_binary 
+tag_old_static -tag_any_white -tcl +terminfo +termresponse +textobjects +title
 -toolbar +user_commands +vertsplit +virtualedit +visual +visualextra +viminfo 
+vreplace +wildignore +wildmenu +windows +writebackup -X11 -xfontset -xim -xsmp
 -xterm_clipboard -xterm_save 
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -D_FORTIFY_SOURCE=0 -Iproto -DHAVE_CONFIG_H -arch i386 -arch x86_64 -g -Os -pipe
Linking: gcc -arch i386 -arch x86_64 -o vim -lncurses
```

But you should now I can also reproduce it on neovim : 
```
NVIM 0.0.0-alpha+201501130938 (compiled Jan 13 2015 21:44:24)
Commit: 9b4f6fbd33ebd452d472b0333accfcb34e01173b
Build type: RelWithDebInfo
```

I tried the simple fix to be sure where the problem is, but I would miss the missing functionality :(

**Comment by pelodelfuego** [comment]
Ok, i'll try it and keep you in touch.

Just 3 more question:
1/  Acutally, i was wrong with the command to launch, it should be ``` :call SwoopPattern('pattern')```
2/ What append if you try it interactivly: ```:call Swoop()```
3/ I see you use Vundle, did you tried with Pathogen ? there should be no differences but it the only i see between my configuration and yours.

**Comment by jonthn** [comment]
Thanks for your help.

1/ and 2/ with those commands the split window appears without error but if I remove the complete pattern the same error message appears ```E35: No previous regular expression```

3/ In fact it's vim-plug (https://github.com/junegunn/vim-plug) but if I only download the plugin file from vim-swoop and use the minimal .vimrc below I can still reproduce the error
```
set nocompatible
set hidden
```

**Comment by pelodelfuego** [comment]
Okay, i'm trying
Can you find it by by autocompletion command ? i mean does vim indexes ```:call Swoop()``` ?

**Comment by pelodelfuego** [comment]
Good news,
Just reproduce the bug, working on it

**Comment by pelodelfuego** [comment]
Fix it by really simple action, 
Have you **ever** search by using ```*``` on the current word ?

Seems Vim initialize an intern variable the first time you search this way (which is really convenient). As long as you never use the vim functionality, the value of this varible is in undefined state.

For instance i could reproduce the bug but since i search a first time, i can't reproduce it anymore.
Keep me in touch when you try it.

**Comment by jonthn** [comment]
No each time I didn't do anything more than just ```:Swoop``` but indeed when I search using __star__ the problem disappears.
In order to re-establish the problem you just have to remove ```.viminfo```.
So it should be possible that someone disable the usage of viminfo and get this problem each time if he doesn't do a search before, just speculating here.

**Comment by pelodelfuego** [comment]
okay, 
The issue appears when the register ```@/ ``` is not initialized, you can try ```:echo(@/)``` to convince you.
.viminfo is in charge to initialize it normaly.

I'll push a fix soon, thank you for your collaboration.

**Comment by jonthn** [comment]
Ok. No problem I'm happy to help moreover it also helps me.
Thanks again it's a great plugin you've made here.

**Comment by pelodelfuego** [comment]
fixed but introduced a regression (ie issue 14), still working on it
