### ISSUE TITLE
Add `preview_delay` option

### ISSUE THREAD

**Issue by balta2ar** [pelodelfuego/vim-swoop#18]
When you scroll over the results, it's cool that current line is selected in the preview automatically. Sometimes, though, it is a problem: if I just press j to scroll down over results, I can see a delay and vim slows down because vim-swoop tries to preview every line that I go through. How about adding an option: `preview_delay`, which default value would be 0, but if user sets it to, say, 100, preview will be shown only if user stays on the line for 100ms? Thanks.

**Comment by pelodelfuego** [comment]
I agree,
Done.
