### ISSUE TITLE
Sync?

### ISSUE THREAD

**Issue by jeetsukumaran** [pelodelfuego/vim-swoop#2]
Sometimes after moving up and down the swoop list, the main buffer gets out of sync. Is there or can support be added for a command/mapping that will re-sync: e.g., pressing ``SPACE`` in the swoop list will jump to the corresponding line in the main buffer? Sort of like ``<CR>``, but without closing the swoop list and the swoop list remaining in focus?

**Comment by pelodelfuego** [comment]
Hello, 

I'm currently working on a brand new realease which completly redesign the swoop mecanisms.
It will be out soon, 1 week max, and will problably cruch this issue.

However what you can do is map <Space> to s:moveSwoopCursor(). It should make it work.

**Comment by pelodelfuego** [comment]
The new version is available,
It should solve this issue.
