### ISSUE TITLE
Error when starting :SwoopMultili

### ISSUE THREAD

**Issue by rgrinberg** [pelodelfuego/vim-swoop#20]
Can't copy paste so I'll leave a screenshot:

https://www.evernote.com/shard/s417/sh/6425f535-a81a-41c7-bb5e-4231041b1d46/fb643f7cd3062163ab368c49e0e4e66d

It happens when I trigger swoop with the following mapping

```vim
nmap <Leader><Leader> :call SwoopMulti()<CR>
```

**Comment by pelodelfuego** [comment]
Hello, 

What is you mapping for ```:call Swoop()``` ?

Did you think to add:
```
let g:swoopUseDefaultKeyMap = 0
```
to your .vimrc ?
(since you have a swoop error, it should be)

**Comment by rgrinberg** [comment]
Hi, here are all my settings for swoop:

``` vim
let g:swoopUseDefaultKeyMap = 0
nmap <Leader><Leader> :call SwoopMulti()<CR>
vmap <Leader><Leader> :call SwoopMultiSelection()<CR>
```

**Comment by pelodelfuego** [comment]
It worked for me so the reason of your issue is not the mapping.

can you post me:
your vim version
your .vimrc
the list of plugin you use ?

**Comment by rgrinberg** [comment]
Here's my vimrc https://github.com/rgrinberg/vimrc/blob/master/.vimrc#L365

But it's very massive so I don't think we'll be able to get much use of it. I use Vim 7.640

**Comment by pelodelfuego** [comment]
Ok, so can you provide me a scenario to reproduce the bug ?

**Comment by rgrinberg** [comment]
I can't reproduce this bug anymore. I assume it's been fixed somehow.
