### ISSUE TITLE
Remap exit key

### ISSUE THREAD

**Issue by rgrinberg** [pelodelfuego/vim-swoop#23]
I'd like to exit swoop mode using `q` in normal mode and `C-c` in any mode. Anyway to accomplish this?

**Comment by pelodelfuego** [comment]
Hey!

It could be added but since ```q``` is used for macro it seems not to be a good idea to me.
Recursive macro are really usefull in swoop mode.

However I agree an exit in unite way would be coherent.
Do you have any idea on how we could do it ?

**Comment by pelodelfuego** [comment]
One year after, a lot of time to think about it ;)
So do you have any suggestion for enchancing the behaviour and keep recursive macro / vim  consitent behaviour ?
