### ISSUE TITLE
Missing in-vim documentation

### ISSUE THREAD

**Issue by Bew78LesellB** [pelodelfuego/vim-swoop#29]
Currently there is no `:h swoop.txt` help inside vim

I hope it'll be added soon
Thanks a lot, it's an awesome plugin :)

**Comment by pelodelfuego** [comment]
Welcome,
my pleasure, I just ported a functionality I was missing from emacs =)

Yep indeed no documentation yet, I'll have to do it.
Keep you in touch about it !

**Comment by pelodelfuego** [comment]
All done =)
