### ISSUE TITLE
E117: Unknown function: matchaddpos

### ISSUE THREAD

**Issue by jeetsukumaran** [pelodelfuego/vim-swoop#3]
When invoking using ``\l`` or ``\ml``:

    E486: Pattern not found:
    Error detected while processing function <SNR>55_cursorMoved..<SNR>55_displayHighlight:
    line   11:
    E117: Unknown function: matchaddpos

**Comment by pelodelfuego** [comment]
Strange, 
matchaddpos() is a built in vim function, 

What is your vim version?

**Comment by jeetsukumaran** [comment]
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Apr 21 2014 14:54:22)
MacOS X (unix) version
Included patches: 1-258

I guess matchaddpos() was added *very* recently, to the point that it is 
not even included in the current stable releases. You could stick to 
using it, but I would suggest an alternate approach if you want to allow 
the vast majority of Vim users to be able to adopt your plugin. It might 
be decades before this percolates out to the majority code base!

-- jeet

On 1/8/15 5:11 AM, pelodelfuego wrote:
> Strange,
> matchaddpos() is a built in vim function,
>
> What is your vim version?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pelodelfuego/vim-swoop/issues/3#issuecomment-69159806>.
>

-- 



--------------------------------------
Jeet Sukumaran
--------------------------------------
jeetsukumaran@gmail.com
--------------------------------------
Blog/Personal Pages:
    http://jeetworks.org/
GitHub Repositories:
    http://github.com/jeetsukumaran
Photographs (as stream):
    http://www.flickr.com/photos/jeetsukumaran/
Photographs (by galleries):
    http://www.flickr.com/photos/jeetsukumaran/sets/
--------------------------------------

**Comment by pelodelfuego** [comment]
hello,
I'm not sure that is the true reason of this issue because matchaddpos() seems to be added before the version you're using.

I've seen it should be packed in your version [here](https://github.com/b4winckler/macvim/search?utf8=%E2%9C%93&q=matchaddpos).

However, what you said about compatibility still true, i'll consider a solution.

Anyway, let's figure out the issue you have,
What do you get when you execute:
```
:h matchaddpos()
```

**Comment by jeetsukumaran** [comment]
I get:

	E149: Sorry, no help for matchaddpos()


On 1/8/15 12:17 PM, pelodelfuego wrote:
> hello,
> I'm not sure that is the true reason of this issue because matchaddpos()
> seems to be added before the version you're using.
>
> I've seen it should be packed in your version here
> <https://github.com/b4winckler/macvim/search?utf8=%E2%9C%93&q=matchaddpos>.
>
> However, what you said about compatibility still true, i'll consider a
> solution.
>
> Anyway, let's figure out the issue you have,
> What do you get when you execute:
>
> |:h matchaddpos()
> |
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pelodelfuego/vim-swoop/issues/3#issuecomment-69213508>.
>

-- 



--------------------------------------
Jeet Sukumaran
--------------------------------------
jeetsukumaran@gmail.com
--------------------------------------
Blog/Personal Pages:
    http://jeetworks.org/
GitHub Repositories:
    http://github.com/jeetsukumaran
Photographs (as stream):
    http://www.flickr.com/photos/jeetsukumaran/
Photographs (by galleries):
    http://www.flickr.com/photos/jeetsukumaran/sets/
--------------------------------------

**Comment by pelodelfuego** [comment]
Okay, juste pushed an update on master, 
it should solve the issue (and be compatible for older vim versions)
Can you tell me if it works ?

**Comment by jeetsukumaran** [comment]
Thanks!

This works.

A few more things:

(1) the colors (light cyan bg) make it impossible to see when I have 
light-colored text. This needs to be customized

(2) the default key-mappings need to be allowed to be customized. E.g., 
<Leader>l conflicts with other mappings

(3) It would be nice to expose a command, e.g., "Swoop <exp>" or "Swoop! 
<exp>"

Do you want me to submit these as separate issues?



On 1/8/15 12:50 PM, pelodelfuego wrote:
> Okay, juste pushed an update on master,
> it should solve the issue (and be compatible for older vim versions)
> Can you tell me if it works ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pelodelfuego/vim-swoop/issues/3#issuecomment-69218731>.
>

-- 



--------------------------------------
Jeet Sukumaran
--------------------------------------
jeetsukumaran@gmail.com
--------------------------------------
Blog/Personal Pages:
    http://jeetworks.org/
GitHub Repositories:
    http://github.com/jeetsukumaran
Photographs (as stream):
    http://www.flickr.com/photos/jeetsukumaran/
Photographs (by galleries):
    http://www.flickr.com/photos/jeetsukumaran/sets/
--------------------------------------

**Comment by pelodelfuego** [comment]
Thanks for your feedback
1/ I'll improve the doc in order to let people know how to edit the highlight
2/ You can override the mapping in your .vimrc as shown in the doc
3/ I'm doing it

**Comment by jeetsukumaran** [comment]
Thanks, again.

For (1), thanks; I suggest that the default highlight be a linked to an 
existing color, e.g., IncSearch or Search. That way, the default will 
Just Work regardless of the user color. So, something like:

     if !hlexists('SwoopBufferLineHi')
         hi! link SwoopBufferLineHi Search
     endif
     if !hlexists('SwoopPatternHi')
         hi! link SwoopPatternHi IncSearch
     endif

For (2), note that even defining a custom mapping in .vimrc does not 
prevent the `<Leader>l` and `<Leader>ml` from being mapped. An option to 
disable the default mapping should be provided (e.g. by defining 
`g:swoop_enable_keymaps=0``). Even better and more Vim-like (IMHO), 
would be to expose a <Plug> and provide a suggested mapping in the doc, 
but leave the actual mapping to the user. Or both.

(3) Appreciated!

Nice plugin, BTW! I think I will be using it a lot!

On 1/8/15 3:24 PM, pelodelfuego wrote:
> Thanks for your feedback
> 1/ I'll improve the doc in order to let people know how to edit the
> highlight
> 2/ You can override the mapping in your .vimrc as shown in the doc
> 3/ I'm doing it
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pelodelfuego/vim-swoop/issues/3#issuecomment-69243121>.
>

-- 



--------------------------------------
Jeet Sukumaran
--------------------------------------
jeetsukumaran@gmail.com
--------------------------------------
Blog/Personal Pages:
    http://jeetworks.org/
GitHub Repositories:
    http://github.com/jeetsukumaran
Photographs (as stream):
    http://www.flickr.com/photos/jeetsukumaran/
Photographs (by galleries):
    http://www.flickr.com/photos/jeetsukumaran/sets/
--------------------------------------

**Comment by pelodelfuego** [comment]
Hey again, 

1/ I've been working on adaptable coloscheme depending on light or dark theme. I bet you are in dark one ? (indeed, render was aweful)
Since i work in light theme i just totally forgot to consider dark one =). Anyway, it is done.
I already thought to link to existing color but in swoop you have 2 pattern matching so i think this is not the best solution.

2/ Your right, this is better, i'll implement it soon

3/ It is done and you're welcome, my pleasure to add functionality !

**Comment by jeetsukumaran** [comment]
For the colors, the current logic is inefficient and not robust. E.g., user may use a dark color scheme but not set the variable correctly. More problematic is if user changes color scheme halfway through a session.  Furthermore the use of `redir` etc. is all a lot of overhead.

I just tried my logic, and it works well in all situations, is flexible and robust. Note that there is no problem supporting matching 2 patterns. Simply link to another color, e.g. ``Warning`` and ``Error``.

     if !hlexists('SwoopBufferLineHi')
         "hi! link SwoopBufferLineHi Search
         hi! link SwoopBufferLineHi Warning
     endif
     if !hlexists('SwoopPatternHi')
         "hi! link SwoopPatternHi IncSearch
         hi! link SwoopPatternHi Error
     endif

**Comment by jeetsukumaran** [comment]
Incidentally, with the way it is set up now, the colors I give in my `vimrc` is ignored/overridden.

**Comment by pelodelfuego** [comment]
Actually, background is a "discrete" vim variable, it can only be 'light' or 'dark' so the bad variable set is not possible.

About the case the user chage coloscheme during a session, the highlight are set during the initSwoop() function so it won't affect him unless he toggle while he is using swoop (i bet it can't append in a normal use case).

Anyway, i'll try your solution tomorrow to see if i find color which match what i want, I keep you in touch.
Thanks a lot for your feedback and good night.

**Comment by pelodelfuego** [comment]
Checked you solution,
Still, I think user should not have same highlight for different things.
However, i will figure out a solution to allow overriding default highlight (like for keymap).

**Comment by pelodelfuego** [comment]
I've add option to disable defaut mapping

**Comment by pelodelfuego** [comment]
And an option to put custom highlight

**Comment by jeetsukumaran** [comment]
Great! Thanks!
