### ISSUE TITLE
vim 8 on windows: "E937: Attempt to delete a buffer that is in use" on SwoopQuit()

### ISSUE THREAD

**Issue by MagicDuck** [pelodelfuego/vim-swoop#31]
I fixed it by swapping the order of those 2 lines at the bottom:
```
    autocmd!    BufWinLeave   swoopBuf   :call  SwoopQuit()
    autocmd!    BufWinLeave   swoopBuf   :call  delete('./swoopBuf')
```
I think it's trying to delete the buffer while it's "locked" cause the file is there probably due to : https://groups.google.com/forum/#!topic/vim_dev/SpIrI4-0nOw

**Comment by pelodelfuego** [comment]
Ty for contributing,
Yeah that's a good insight, 

Do you want to do a PR ? or you prefer me to fix it ?

Cheers

**Comment by MagicDuck** [comment]
FYI, I've created https://github.com/pelodelfuego/vim-swoop/pull/32

**Comment by pelodelfuego** [comment]
merged =)

**Comment by balta2ar** [comment]
@pelodelfuego Continuing here.

> Did you tried to delete the 'swoopBuf' file ?

Yes I made sure there is no `swoopBuf` file.

> Also, are you sure it comes from this commit ?

Yes I manually git checkouted to 539004b and the problem disappeared.

> could you post your .nvimrc file please ?

``` vim
if &compatible
  set nocompatible
endif

" Install plug as follows:
" curl -fLo ~/.local/share/nvim/site/autoload/plug.vim \
"   --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
call plug#begin('~/.vim/plugged')

"Plug 'pelodelfuego/vim-swoop', {'commit': 'a5ef85b'}
Plug 'pelodelfuego/vim-swoop'

call plug#end()

filetype plugin indent on
syntax enable
set nocompatible
```
I'm using neovim from master branch (https://github.com/neovim/neovim/commit/4a511de881efcf9b759c7babdeb0e31242d62c2e).

**Comment by balta2ar** [comment]
Yeah, thanks! Things are back to normal. Sorry I made you do it hackish way for neovim.

**Comment by pelodelfuego** [comment]
haha no problems =)

Cool, Ty for your feedback and your help,
Have a nice day !
