### ISSUE TITLE
Error while closing swoop buffer

### ISSUE THREAD

**Issue by naseer** [pelodelfuego/vim-swoop#36]
"swoopBuf" [Modified][New file] 23 lines --4%--
"swoopBuf" [Modified][New file] 23 lines --4%--
"swoopBuf" [Modified][New file] 23 lines --4%--
"swoopBuf" [Modified][New file] 23 lines --4%--
"swoopBuf" [Modified][New file] 23 lines --4%--
"swoopBuf" [Modified][New file] 23 lines --4%--
"swoopBuf" [Modified][New file] 23 lines --4%--
"swoopBuf" [Modified][New file] 23 lines --4%--
"swoopBuf" [Modified][New file] 23 lines --4%--
"swoopBuf" [Modified][New file] 23 lines --4%--
"swoopBuf" [Modified][New file] 23 lines --4%--
"swoopBuf" [Modified][New file] 23 lines --4%--
Error detected while processing function SwoopQuit:
line    2:
E937: Attempt to delete a buffer that is in use

**Comment by pelodelfuego** [comment]
Hi,

The issue should be fixed on master, can you ack ?

**Comment by naseer** [comment]
Still reproducible - 

This is the top commit I have
```
commit a67e205e46449e47c1c469f24c5de25dce3e7fdf
Author: pelodelfuego <clement.crepy@gmail.com>
Date:   Fri Jun 9 16:47:47 2017 +0100

    fix swoopBuf interferences
```


```
E385: search hit BOTTOM without match for: diag
"swoopBuf" [Modified][New file] 1 line --100%--
"swoopBuf" [Modified][New file] 7 lines --14%--
"swoopBuf" [Modified][New file] 7 lines --14%--
Error detected while processing function SwoopQuit:
line    4:
E937: Attempt to delete a buffer that is in use
"~/.vimrc" 352 lines --49%--
"swoopBuf" [Modified][New file] 1 line --100%--
"swoopBuf" [Modified][New file] 1 line --100%--
"swoopBuf" [Modified][New file] 5 lines --20%--
"swoopBuf" [Modified][New file] 5 lines --20%--
"swoopBuf" [New] 5L, 87C written
Error detected while processing function SwoopQuit:
line    4:
E937: Attempt to delete a buffer that is in use
```

**Comment by naseer** [comment]
What is the recommended way of exiting swoop? I'm using a regular :q!  (I don't need to save the swoop buf in general)

**Comment by pelodelfuego** [comment]
Hi,

Sorry for late reply,
I think you have a swoopBuf already open in you vim session (due to vim-swoop before the fix).
Can you check if you have a 'swoopBuf' file saved on your computer ?

If so you can delete it (file and buffer) and the problem should not appear anymore.

I usually do :q without !

**Comment by naseer** [comment]
I exited vim completely and looked for swoopBuf in my current directory and home directory - it only shows up when running swoop


![swoop](https://user-images.githubusercontent.com/35860/27044676-69856c46-4f6c-11e7-8e41-33746beabcd4.gif)

**Comment by pelodelfuego** [comment]
Hum,
Could you post your .vimrc or try to reproduce with a minimal environment ?
It may be due to an autocommands in your configuration (like save at exit).

**Comment by naseer** [comment]
I'm using neovim - I tried to use the same vimrc with regular vim and I couldn't reproduce it. I'm closing this, since this is likely just a neovim issue, sorry for the false alarm - I haven't had issues with plugins in neovim in general, but I guess this plugin is exposing an issue there.
