### ISSUE TITLE
Configuration variables are script-scope, need to be global scope

### ISSUE THREAD

**Issue by jeetsukumaran** [pelodelfuego/vim-swoop#4]
The configuration variables given
    
    let s:regexMode = 0 
    let s:autoInserMode = 0 

cannot be set by the user conventionally in `~/.vimrc` because they are script variables. They should be globally scoped (e.g., `g:swoop_regex_mode` and `g:swoop_autoinsert_mode`)

**Comment by pelodelfuego** [comment]
Oups, right, i'm on it
