### ISSUE TITLE
Buffer Not Deleted When Navigating and Quitting

### ISSUE THREAD

**Issue by d0liver** [pelodelfuego/vim-swoop#40]
https://github.com/pelodelfuego/vim-swoop/commit/cd649add12e8ada4df78a2201b4af7d8285a6314 causes the buffer to not be deleted when SwoopQuit() is called. Tested against vim 8.0 and NeoVim.

**Comment by pelodelfuego** [comment]
Hello,

Thank you for the investigation !

I checked and succeed to reproduce using your comment, I agree there is an issue.
However, I'm not sure on how to solve this:

My understanding is that upon writing the swoop buffer, vim keep a track of this 'regular' buffer being edited.
As explained in issue #33, we need to have a 'regular' buffer to trigger the WriteCmd event (using :w to apply the swoop buffer).

I don't think we can have the benefits of a special and a regular buffer at the same time,
I close for now but please let me know if you know a way we could get the best of both worlds.
