### ISSUE TITLE
Swoop clobbers the default register

### ISSUE THREAD

**Issue by jeetsukumaran** [pelodelfuego/vim-swoop#5]
Invoking swoop results in the default register being overwritten. Swoop should avoid this by explicitly specifying the "black hole" register when deleting content (``"_``).

**Comment by pelodelfuego** [comment]
hey,
as a beginner in vim usage (i began 1 month ago to write this plugin actually), i do not understandwhat behaviour do you expect.
Could you detail it please ?

**Comment by jeetsukumaran** [comment]
Imagine I yank a word, e.g. "hello" (e.g., I visually select a word, "hello", and press ``y``). When I press `p` (for "put"/paste), the word "hello" appears, right? Well, *not* if invoke Swoop and close it. If I open Swoop and then close it (with out without modifications) and then press `p`, then the Swoop buffer contents appear instead of "hello". This is because there are some place where you delete lines, and these deleted lines get placed into the default buffer, overwriting whatever is there.

Fortunately, the fix is easy and the following functions starting at line 207 need to be modified:

    function! s:displaySwoopResult(beforeCursorMoved)
        let pattern = s:getSwoopPattern()
        let bufferList = s:getSwoopBufList()

        let results = s:getSwoopResultsLine(bufferList, pattern)
        exec "buffer ". s:swoopBuf
        if s:multiSwoop == 0
            silent! exec '2,$"_d'
            call append(1, results)
        else
            silent! exec '3,$"_d'
            call append(2, results)
        endif
        call setpos('.', a:beforeCursorMoved)
    endfunction

    function! s:displaySwoopBuffer(beforeCursorMoved)
        exec "buffer ". s:swoopBuf
        silent! exec '3,$"_d'

        let swoopBufList = s:getSwoopBufList()
        let swoopBufStrList = map(copy(swoopBufList), 's:getBufferStr(v:val)')

        call append(2, swoopBufStrList)
        call setpos('.', a:beforeCursorMoved)
    endfunction

Check out the modifications to line 215, 218, and 226, where, e.g.

    silent! exec "2,$d"

is replaced with:

   silent! exec '2,$"_d'

The ``"_`` preceding the delete command ensures that the deleted text gets placed in the "black hole" register, leaving the main copy/past registers untouched.

BTW, I could clone and fix this myself and then submit a pull request if you prefer. But I think that in this early stage it might better to work this way? If you disagree, let me know.

**Comment by jeetsukumaran** [comment]
By the way, for a beginner, this is really fantastic work. In fact, even if you were an expert with thousands of hours, this is *still* great work! Congratulations and Kudos!

**Comment by pelodelfuego** [comment]
Indeed it is a better behaviour, i modified it.

Thanks for your compliments, actually I had other experiences with different languages and come from emacs so i already played with elisp but i begin in vim and vimscript.

By the way, Thanks a lot for your feedback and advises, it is precious.

**Comment by pelodelfuego** [comment]
Actally just saw an issue with ```"2,$d"```, the swoopBuf won't clear itself.
I reverted it on master but keep in on dev to figure out a solution.

**Comment by pelodelfuego** [comment]
The issue was just anout the syntax,
correct form is ```silent! exec "2,$d_"```

found on:
http://vim.wikia.com/wiki/Power_of_g
