### ISSUE TITLE
``SwoopMultiPattern()`` needs to explicitly set the first line even if no buffer pattern is passed

### ISSUE THREAD

**Issue by jeetsukumaran** [pelodelfuego/vim-swoop#6]
The function ``SwoopMultiPattern()`` needs to explicitly clear the first line if no buffer names are passed.

I.e., instead of:

    function! SwoopMultiPattern(pattern, ...)
        call SwoopMulti()
        if a:0 == 1
            call setline(1, a:000)
        endif
        call setline(2, a:pattern)
    endfunction

we need:

    function! SwoopMultiPattern(pattern, ...)
        call SwoopMulti()
        if a:0 == 1
            call setline(1, a:000)
        else
            call setline(1, "")
        endif
        call setline(2, a:pattern)
    endfunction

**Comment by pelodelfuego** [comment]
I agree, done
