### ISSUE TITLE
``SwoopMulti()`` needs to explicitly clear the first line

### ISSUE THREAD

**Issue by jeetsukumaran** [pelodelfuego/vim-swoop#7]
As before, I *think* that the first line needs to be cleared for consistent
correct behavior:

    function! SwoopMulti()
        call setline(1, "")
        if s:multiSwoop == 1
            call setline(2, "")
            execute ":2"
        endif
        if s:multiSwoop == -1
            let s:multiSwoop = 1
            call s:initSwoop()
            call append(1, [""])
            execute ":2"
        endif
        if s:multiSwoop == 0
            let s:multiSwoop = 1
            let pattern = getline(1)
            call setline(1, "")
            call append(1, [pattern])
            execute ':1'
        endif

        if s:autoInsertMode == 1
            startinsert
        endif
    endfunction

**Comment by pelodelfuego** [comment]
I disagree, the objectcive when invoking MultiSwoop again is to edit the pattern if you put a bad one.

**Comment by jeetsukumaran** [comment]
You are correct. It works OK as it is.
