### ISSUE TITLE
Swoop exposes functions, but not commands from the command line.

### ISSUE THREAD

**Issue by jeetsukumaran** [pelodelfuego/vim-swoop#9]
The documentation says that Swoop exposes two commands, ``SwoopPattern(pattern)`` and ``SwoopMultiPattern(searchPattern)``. Actually, those are functions. Invoking them from the command line is rather clumsy ("``:call SwoopPattern('text')``").

I would suggest adding something like the following to expose a real command:

    function! s:RunSwoop(searchPattern, isMulti)
        if empty(a:isMulti)
            call SwoopPattern(a:searchPattern)
        else
            call SwoopMultiPattern(a:searchPattern)
        endif
    endfunction
    command! -bang -nargs=* Swoop :call <SID>RunSwoop(<q-args>, '<bang>')

With this, the user can type "``:Swoop <pattern>``" to search the current buffer for a pattern or "``:Swoop! <pattern>``" to search all buffers. Of course, you can also just type "``:Swoop``" or "``:Swoop!``" to start swoop.

**Comment by pelodelfuego** [comment]
I agree the actual exposure is not good yet (ie ```:call SwoopPattern('text')``` ) but calling Swoop this way block the magic search (ie: ```\<Space\>``` for ```.*```).

An alternative could be to return a fake value in order to access it by:
```SwoopPattern('text')```
But i do not find it elegant. What do you think ?

**Comment by pelodelfuego** [comment]
After reflexion, you solution is the better one, just pushe it. Thanks.
